version: "3.8"

services:
  angular-init:
    build:
      context: .
    image: empleo/angular-build
    command: sh -c "npm run build && cp -r dist/* /dist/ && echo 'Build complete'"
    volumes:
      - angular-dist:/dist
    networks:
      - system_api-network

volumes:
  angular-dist:
    external: true

networks:
  system_api-network:
    external: true
