services:
  angular:
    container_name: nocodeapi-angular
    build:
      context: .
      network: host
    restart: always
    pull_policy: build
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl/empleo_at.crt:/etc/ssl/cert.crt  # SSL-Zertifikat mounten
      - /etc/ssl/empleo_at.key:/etc/ssl/cert.key  # Privater Schlüssel mounten
      - /etc/ssl/empleo_at.ca-bundle:/etc/ssl/ca-bundle.crt
    networks:
      - nocodeapi-network


networks:
  nocodeapi-network:
    driver: bridge
