version: "3.8"

services:
  angular-builder:
    build:
      context: .
    image: empleo/angular-build
    command: tail -f /dev/null
    volumes:
      - angular-dist:/dist
    networks:
      - system_api-network

volumes:
  angular-dist:
    external: true

networks:
  system_api-network:
    driver: bridge
