# HTTPS-Server für empleo.at
server {
    listen 443 ssl;
    server_name empleo.at;

    ssl_certificate /etc/ssl/cert.crt;         # Gemountetes SSL-Zertifikat
    ssl_certificate_key /etc/ssl/cert.key;     # Gemounteter privater Schlüssel
    ssl_trusted_certificate /etc/ssl/ca-bundle.crt; # CA-Bundle

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html; # SPA Unterstützung
    }
}

# HTTP-Server für empleo.at (Umleitung zu HTTPS)
server {
    listen 80;
    server_name empleo.at;

    # Umleitung von HTTP zu HTTPS
    return 301 https://$host$request_uri;
}
